export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS';
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';
export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL';
export const FACEBOOK_AUTH_SUCCESS = 'FACEBOOK_AUTH_SUCCESS';
export const FACEBOOK_AUTH_FAIL = 'FACEBOOK_AUTH_FAIL';
export const LOGOUT = 'LOGOUT';
export const ERROR_MESSAGE = 'ERROR_MESSAGE'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE'

/* MAP */
export const DURATION_SLIDER_VALUE = 'DURATION_SLIDER_VALUE';
export const DURATION_MAX = 'DURATION_MAX'

export const ELEVATION_SLIDER_VALUE = 'ELEVATION_SLIDER_VALUE';
export const ELEVATION_MAX = 'ELEVATION_MAX'

export const DISTANCE_SLIDER_VALUE = 'DISTANCE_SLIDER_VALUE';
export const DISTANCE_MAX = 'DISTANCE_MAX'

export const SLIDER_RELOAD_VAR = 'SLIDER_RELOAD_VAR';

export const MAP_OFFSET = 'MAP_OFFSET'
export const MAP_BOUNDS = 'MAP_BOUNDS'
export const DIFFICULTY_SELECTION = 'DIFFICULTY_SELECTION'
export const TOUR_SELECTION = 'TOUR_SELECTION'
export const MAP_SEARCHSTRING = 'MAP_SEARCHSTRING'
export const HUTTYPE_SELECTION = 'HUTTYPE_SELECTION'
export const LOCATION_SELECTION = 'LOCATION_SELECTION'
export const RESET_SELECTION = 'RESET_SELECTION'

export const D3_SELECTION = 'D3_SELECTION'
export const D3_INDEX = 'D3_INDEX'
export const D3_ELEVATION = 'D3_ELEVATION'