# Generated by Django 4.2 on 2023-04-10 20:26

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mountain_huts.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MountainHut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('text', tinymce.models.HTMLField()),
                ('image', models.ImageField(default='tour/default.jpg', upload_to=mountain_huts.models.upload_to, verbose_name='Image')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('hut_type', models.CharField(choices=[('alm', 'Alm'), ('huette', 'Huette'), ('gasthof', 'Gasthof'), ('sonstige', 'Sonstige')], default='Huette', max_length=10)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hut_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
