# Generated by Django 4.2 on 2023-04-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_huts', '0004_hutgallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HutGallery',
        ),
    ]
