# Generated by Django 4.2 on 2023-04-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_huts', '0006_hutgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountainhut',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mountainhut',
            name='telephone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mountainhut',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
