# Generated by Django 4.2 on 2023-04-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_huts', '0008_mountainhut_subtitle_alter_mountainhut_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountainhut',
            name='subtitle',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
