# Generated by Django 4.2 on 2023-04-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_huts', '0010_alter_mountainhut_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountainhut',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, null=True, unique_for_date='created'),
        ),
    ]
