# Generated by Django 4.2 on 2023-04-30 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_region_parent'),
        ('mountain_huts', '0011_alter_mountainhut_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountainhut',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='huts', to='geography.region'),
        ),
    ]
