# Generated by Django 4.2 on 2023-04-30 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mountain_huts', '0012_mountainhut_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountainhut',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='hut_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mountainhut',
            name='text',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
