# Generated by Django 4.2 on 2023-04-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_huts', '0013_alter_mountainhut_author_alter_mountainhut_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountainhut',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1, null=True),
        ),
    ]
