# Generated by Django 4.2 on 2023-04-30 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_region_parent'),
        ('mountain_huts', '0014_alter_mountainhut_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mountainhut',
            old_name='parent',
            new_name='region',
        ),
        migrations.AddField(
            model_name='mountainhut',
            name='gebirge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='huts', to='geography.gebirge'),
        ),
        migrations.AddField(
            model_name='mountainhut',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='huts', to='geography.zone'),
        ),
    ]
