# Generated by Django 4.2 on 2023-05-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_huts', '0017_alter_mountainhut_author_alter_mountainhut_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountainhut',
            name='altitude',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
