# Generated by Django 4.2 on 2023-05-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_huts', '0018_mountainhut_altitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mountainhut',
            name='zone',
        ),
        migrations.AddField(
            model_name='mountainhut',
            name='overnight',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
