# Generated by Django 4.2 on 2023-05-16 08:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_huts', '0020_mountainhut_offseason_mountainhut_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountainhut',
            name='altitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mountainhut',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='mountainhut',
            name='subtitle',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mountainhut',
            name='text',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
