# Generated by Django 4.2 on 2023-04-09 14:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touren', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='track',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326),
        ),
    ]
