# Generated by Django 4.2 on 2023-04-17 06:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import pictures.models
import touren.models


class Migration(migrations.Migration):

    dependencies = [
        ('touren', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='poly',
        ),
        migrations.AddField(
            model_name='tour',
            name='difficulty',
            field=models.CharField(choices=[('leicht', 'LEICHT'), ('mittel', 'MITTEL'), ('schwierig', 'SCHWIERIG')], default='schwierig', max_length=10),
        ),
        migrations.AddField(
            model_name='tour',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='geojson_track',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='gpxfile',
            field=models.FileField(null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='track',
            field=django.contrib.gis.db.models.fields.LineStringField(dim=3, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=pictures.models.PictureField(aspect_ratios=[None], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, default='tour/default.jpg', file_types=['JPEG'], grid_columns=12, pixel_densities=[1, 2], upload_to=touren.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, unique_for_date='published'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=touren.models.upload_to)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='touren.tour')),
            ],
        ),
    ]
