# Generated by Django 4.2 on 2023-04-09 15:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touren', '0002_tour_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='poly',
        ),
        migrations.AlterField(
            model_name='tour',
            name='track',
            field=django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326),
        ),
    ]
