# Generated by Django 4.2 on 2023-04-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touren', '0005_remove_tour_geotrack_tour_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='gpxfile',
            field=models.FileField(null=True, upload_to='files'),
        ),
    ]
