# Generated by Django 4.2 on 2023-04-21 10:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('touren', '0005_tour_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='season',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('mai', 'Mai'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('octobre', 'Octobre'), ('november', 'November'), ('decembre', 'Decembre')], default=None, max_length=100),
        ),
    ]
