# Generated by Django 4.2 on 2023-04-09 17:05

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touren', '0006_tour_gpxfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='track',
            field=django.contrib.gis.db.models.fields.LineStringField(dim=3, null=True, srid=4326),
        ),
    ]
