# Generated by Django 4.2 on 2023-04-21 10:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('touren', '0006_alter_tour_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='season',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'Mai'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'Octobre'), ('11', 'November'), ('12', 'Decembre')], default=None, max_length=100),
        ),
    ]
