# Generated by Django 4.2 on 2023-04-13 08:02

from django.db import migrations
import galleryfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('touren', '0008_tour_tour_duration_alter_tour_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='gallery',
            field=galleryfield.fields.GalleryField(blank=True, null=True, target_model='galleryfield.BuiltInGalleryImage', verbose_name='Photos'),
        ),
    ]
