# Generated by Django 4.2 on 2023-04-24 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touren', '0008_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='parent',
        ),
        migrations.AddField(
            model_name='tour',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regionen', to='touren.region'),
        ),
    ]
