# Generated by Django 4.2 on 2023-04-13 09:11

from django.db import migrations, models
import django.db.models.deletion
import touren.models


class Migration(migrations.Migration):

    dependencies = [
        ('touren', '0009_tour_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='gallery',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=touren.models.upload_to)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='touren.tour')),
            ],
        ),
    ]
