# Generated by Django 4.2 on 2023-04-30 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('touren', '0010_gebirge_zone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gebirge',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
        migrations.AlterField(
            model_name='tour',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regionen', to='geography.region'),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
