# Generated by Django 4.2 on 2023-04-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touren', '0011_tour_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='geojson_track',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='distance',
            field=models.FloatField(null=True),
        ),
    ]
