# Generated by Django 4.2 on 2023-05-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touren', '0011_delete_gebirge_delete_zone_alter_tour_region_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='published',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, unique_for_date='created'),
        ),
    ]
