# Generated by Django 4.2 on 2023-05-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touren', '0012_alter_tour_options_rename_published_tour_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='distance',
            field=models.IntegerField(null=True),
        ),
    ]
