# Generated by Django 4.2 on 2023-05-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touren', '0013_alter_tour_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='elevation_gain',
            field=models.FloatField(null=True),
        ),
    ]
