# Generated by Django 4.2 on 2023-05-08 10:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touren', '0015_tour_elevation_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='steps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None),
        ),
    ]
