# Generated by Django 4.2 on 2023-05-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touren', '0018_tour_fitness_difficulty_tour_tech_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='fitness_difficulty',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tech_difficulty',
        ),
        migrations.AddField(
            model_name='hochtour',
            name='fitness_difficulty',
            field=models.CharField(choices=[('leicht', 'LEICHT'), ('mittel', 'MITTEL'), ('schwierig', 'SCHWIERIG')], default='schwierig', max_length=10),
        ),
        migrations.AddField(
            model_name='hochtour',
            name='tech_difficulty',
            field=models.CharField(choices=[('leicht', 'LEICHT'), ('mittel', 'MITTEL'), ('schwierig', 'SCHWIERIG')], default='schwierig', max_length=10),
        ),
        migrations.AlterField(
            model_name='tour',
            name='difficulty',
            field=models.CharField(default='schwierig', editable=False, max_length=10),
        ),
    ]
