# Generated by Django 4.2 on 2023-05-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touren', '0019_remove_tour_fitness_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hikeandfly',
            name='fitness_difficulty',
            field=models.CharField(choices=[('leicht', 'LEICHT'), ('mittel', 'MITTEL'), ('schwierig', 'SCHWIERIG')], default='schwierig', max_length=10),
        ),
        migrations.AddField(
            model_name='hikeandfly',
            name='tech_difficulty',
            field=models.CharField(choices=[('leicht', 'LEICHT'), ('mittel', 'MITTEL'), ('schwierig', 'SCHWIERIG')], default='schwierig', max_length=10),
        ),
        migrations.AddField(
            model_name='skitour',
            name='fitness_difficulty',
            field=models.CharField(choices=[('leicht', 'LEICHT'), ('mittel', 'MITTEL'), ('schwierig', 'SCHWIERIG')], default='schwierig', max_length=10),
        ),
        migrations.AddField(
            model_name='skitour',
            name='tech_difficulty',
            field=models.CharField(choices=[('leicht', 'LEICHT'), ('mittel', 'MITTEL'), ('schwierig', 'SCHWIERIG')], default='schwierig', max_length=10),
        ),
        migrations.AddField(
            model_name='wandern',
            name='fitness_difficulty',
            field=models.CharField(choices=[('leicht', 'LEICHT'), ('mittel', 'MITTEL'), ('schwierig', 'SCHWIERIG')], default='schwierig', max_length=10),
        ),
        migrations.AddField(
            model_name='wandern',
            name='tech_difficulty',
            field=models.CharField(choices=[('leicht', 'LEICHT'), ('mittel', 'MITTEL'), ('schwierig', 'SCHWIERIG')], default='schwierig', max_length=10),
        ),
    ]
