# Generated by Django 4.2 on 2023-05-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touren', '0020_hikeandfly_fitness_difficulty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klettertour',
            old_name='climbing_grades',
            new_name='climbing_grade',
        ),
    ]
