# Generated by Django 4.2 on 2023-05-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touren', '0021_rename_climbing_grades_klettertour_climbing_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hochtour',
            name='fitness_difficulty',
            field=models.CharField(choices=[('F-', 0), ('F', 1), ('F=', 2)], default='schwierig', max_length=10),
        ),
    ]
