# Generated by Django 4.2 on 2023-05-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touren', '0022_alter_hochtour_fitness_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hochtour',
            name='fitness_difficulty',
            field=models.CharField(choices=[('leicht', 'LEICHT'), ('mittel', 'MITTEL'), ('schwierig', 'SCHWIERIG')], default='schwierig', max_length=10),
        ),
        migrations.AlterField(
            model_name='hochtour',
            name='tech_difficulty',
            field=models.CharField(choices=[(0, 'F-'), (1, 'F'), (2, 'F+'), (3, 'PD-'), (4, 'PD'), (5, 'PD+'), (6, 'AD-'), (7, 'AD'), (8, 'AD+-')], default='schwierig', max_length=10),
        ),
    ]
