# Generated by Django 4.2 on 2023-05-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touren', '0023_alter_hochtour_fitness_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hochtour',
            name='tech_difficulty',
            field=models.IntegerField(choices=[(0, 'F-'), (1, 'F'), (2, 'F+'), (3, 'PD-'), (4, 'PD'), (5, 'PD+'), (6, 'AD-'), (7, 'AD'), (8, 'AD+-')], default='schwierig', max_length=10),
        ),
    ]
