# Generated by Django 4.2 on 2023-04-19 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parking_slug_alter_parking_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
