# Generated by Django 4.2 on 2023-04-23 07:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_parking_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='text',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
