# Generated by Django 4.2 on 2023-05-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_parkinggallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='published',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='parking',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, null=True, unique_for_date='created'),
        ),
    ]
