# Generated by Django 4.2 on 2023-05-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_rename_published_parking_created_alter_parking_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='estate',
            field=models.CharField(choices=[('public', 'Oeffentlich'), ('private', 'Privat')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='ground_type',
            field=models.CharField(choices=[('asphalt', 'Asphalt'), ('schotter', 'Schotter'), ('gras', 'Gras'), ('erde', 'Erde')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='short_text',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='toilet',
            field=models.BooleanField(choices=[(True, 'Ja'), (False, 'Nein')], null=True),
        ),
    ]
