# Generated by Django 4.2 on 2023-05-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_parking_estate_parking_ground_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
    ]
