# Generated by Django 4.2 on 2023-05-14 17:12

import blog.models
from django.db import migrations, models
import django.db.models.deletion
import pictures.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogarticle',
            name='text',
        ),
        migrations.CreateModel(
            name='ContentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', pictures.models.PictureField(aspect_ratios=['16/9'], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, default='tour/default.jpg', file_types=['JPEG'], grid_columns=12, pixel_densities=[1, 2], upload_to=blog.models.upload_to, verbose_name='Image')),
                ('image_subtext', models.CharField(max_length=500, null=True)),
                ('text', tinymce.models.HTMLField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='blog.blogarticle')),
            ],
        ),
    ]
