# Generated by Django 4.2 on 2023-05-14 17:33

import blog.models
from django.db import migrations, models
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogarticle_text_contentchunk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogarticle',
            name='category',
        ),
        migrations.AddField(
            model_name='contentchunk',
            name='heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contentchunk',
            name='image',
            field=pictures.models.PictureField(aspect_ratios=['16/9'], blank=True, breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, default='tour/default.jpg', file_types=['JPEG'], grid_columns=12, pixel_densities=[1, 2], upload_to=blog.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='contentchunk',
            name='image_subtext',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contentchunk',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
