# Generated by Django 4.2 on 2023-04-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_use'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='use',
            new_name='user',
        ),
    ]
