# Generated by Django 4.2 on 2023-04-22 18:50

from django.db import migrations
import pictures.models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_newuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=pictures.models.PictureField(aspect_ratios=['16/9', '1/1'], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, default='tour/default.jpg', file_types=['JPEG'], grid_columns=12, pixel_densities=[1, 2], upload_to=users.models.upload_to, verbose_name='Image'),
        ),
    ]
