# Generated by Django 4.2 on 2023-05-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_newuser_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='about',
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=500, verbose_name='about'),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_short',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
