# Generated by Django 4.2 on 2023-04-22 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_feature_article', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogarticle')),
            ],
        ),
    ]
